modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="moretotems"
version="1.0.0"

displayName="More Totems"

authors="Curle, SameButDifferent"

description='''
Adds totems for each mob in the game!
'''

[[dependencies.moretotems]]
   modId="forge"
   mandatory=true
   versionRange="[36,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.moretotems]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.3,1.17)"
   ordering="NONE"
   side="BOTH"
