modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="moretotems"
version="2.2"

displayName="More Totems"

authors="Curle, SameButDifferent"

description='''
Adds more totems for various situations!
'''

[[dependencies.moretotems]]
   modId="forge"
   mandatory=true
   versionRange="[40,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.moretotems]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.18.2,)"
   ordering="NONE"
   side="BOTH"
